config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
      :authorized_applications
  end

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root controller: :rooms, action: :index

  resources :room_messages
  resources :rooms  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :categories, only: [:index] do
        member do
          get 'products'
        end
      end
      resources :carts, only: [:show], param: :cart_id
      resources :carts, only: [:create] do
        resources :cart_items, only: %i[create], param: :product_id
      end
      resources :products, only: [:index]
    end
  end
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  # Loads:
  # @rooms = all rooms
  # @room = current room when applicable
  before_action :load_entities

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end

  def edit; end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="mb-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Create a room
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>
  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the RailsChatTutorial!
      </h4>
      <p>
        We need to talk.
      </p>
      <hr />
      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>
  Creating a room
</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<h1>
  <%= @room.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">
            <div class="col-auto text-center">
              <img src="<%= room_message.user.gravatar_url %>" class="avatar" alt="">
            </div>

            <div class="col">
              <div class="message-content" style= "padding: 5px;
              border: 1px solid $primary;
              border-radius: 5px;
              background: lighten($primary, 10%);
              color: $white;">
                <p class="mb-1">
                  <%= room_message.message %>
                </p>

                <div class="text-right">
                  <small>
                    <%= room_message.created_at %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= simple_form_for @room_message, remote: true do |form| %>
      <div class="input-group mb-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input'
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>
  </div>
</div>
<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <img src="" class="avatar" alt="" data-role="user-avatar">
      </div>

      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text"></p>

          <div class="text-right">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>